services:
  - type: web
    name: vapt-backend
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONUNBUFFERED
        value: true
        python-nmap==0.7.1